### PR TITLE
fixed syntax::ast rustup (expansion incomplete for now)

### PR DESCRIPTION
**Pull request by llogiq**
I'll have to look into the current macro expansion API (the other things I know well enough from clippy). Still, it's a first step. :smile:

### CODE REVIEW

**Comment by Geal** [comment]
Thanks! (and sorry for the delay)

**Comment by llogiq** [comment]
You're welcome. I've thought some more about how mutation testing could work in Rust and [blogged](https://llogiq.github.io/2016/03/24/mutest.html) about it.

What do you think? Does that match what you have in mind with mutant? Or do you have other goals?

**Comment by Geal** [comment]
The mutation counter idea is neat, since it avoids a recompilation per new mutation test. With mutant, I wanted first to explore what could be done. If I wanted to make it usable, I think I would provide two parts in the system.
The first one, the compiler plugin, inserts mutation at different points as specified by the user (like, only test the module A::B) and generates a report of which mutations are possible (id, original position in source, type of mutation available)
The second one, the test runner, takes that report, and launches a new mutation test by passing parameters through env variables (or something else)

The mutations can run a bit like code caves, wrapping pieces of the original code, and redirecting to something else depending on some parameter. It could even be possible to instrument every line of the module to test, since running mutation testing is like fuzzing: you don't care too much about the performance, you launch it and come back a few hours/days later.

If you want, I can give you commit access on this repository, to mess around with stuff and see if your ideas are doable?

**Comment by llogiq** [comment]
I think a thtee-step process would be more beneficial: 
1. A plugin to reorder code (together with a custom driver that collects compiler errors)
2. A lint that uses typeck info to find other mutations, e.g. + vs. -
3. A second plugin that uses the collected information from the former steps to generate the final mutated code + test runner

**Comment by llogiq** [comment]
Oh, and sure, let's join forces. :smile:

**Pull request merged**
